# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='talleres')),
                ('descripcion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('resenia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReseniaUsuario',
            fields=[
                ('taller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mecanicos.Taller')),
                ('resenia', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanicos.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('taller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mecanicos.Taller')),
                ('gomeria', models.BooleanField()),
                ('balanceo', models.BooleanField()),
                ('alineacion', models.BooleanField()),
                ('chapa_y_pintura', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('taller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mecanicos.Taller')),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('mapa', models.URLField()),
            ],
        ),
    ]
